@if (Network::usesMarketSquare())
    <x-table-skeleton
        device="mobile"
        :headers="[]"
        :rows="[
            'text',
            'address',
            'status',
            'number',
            'text',
            'text',
            'number'
        ]"
    />
@else
    <x-table-skeleton
        device="mobile"
        :headers="[]"
        :rows="[
            'text',
            'address',
            'status',
            'number',
            'text',
            'text'
        ]"
    />
@endif
